loading app ryu/tests/switch/tester.py
loading app ryu.controller.ofp_handler
instantiating app ryu.controller.ofp_handler of OFPHandler
instantiating app ryu/tests/switch/tester.py of OfTester
target_dpid=000070b3d56cd016
tester_dpid=0000000000000001
target ofp version=openflow13
tester ofp version=openflow13
Test files directory = ryu/tests/switch/of13/match
--- Test start ---
waiting for switches connection...
dpid=000070b3d56cd016 : Join target SW.
dpid=0000000000000001 : Join tester SW.
match: 00_IN_PORT
    ethernet/ipv4/tcp-->'in_port=1,actions=output:2'                                                     OK
    ethernet/ipv4/tcp-->'in_port=1,actions=output:CONTROLLER'                                            OK
    ethernet/ipv4/tcp-->'in_port=2,actions=output:2'                                                     OK
    ethernet/ipv6/tcp-->'in_port=1,actions=output:2'                                                     OK
    ethernet/ipv6/tcp-->'in_port=1,actions=output:CONTROLLER'                                            OK
    ethernet/ipv6/tcp-->'in_port=2,actions=output:2'                                                     OK
    ethernet/arp-->'in_port=1,actions=output:2'                                                          OK
    ethernet/arp-->'in_port=1,actions=output:CONTROLLER'                                                 OK
    ethernet/arp-->'in_port=2,actions=output:2'                                                          OK
match: 02_METADATA
    ethernet/ipv4/tcp-->'actions=write_metadata:255/0xffffffff,goto_table:1','table_id:1,metadata=255,actions=output:2' OK
    ethernet/ipv4/tcp-->'actions=write_metadata:255/0xffffffff,goto_table:1','table_id:1,metadata=255,actions=output:CONTROLLER' OK
hub: uncaught exception: Traceback (most recent call last):
  File "/home/kawai/ryu/ryu/lib/hub.py", line 54, in _launch
    return func(*args, **kwargs)
  File "/home/kawai/ryu/ryu/tests/switch/tester.py", line 423, in _test_sequential_execute
    report = self._test_file_execute(tests[file_name])
  File "/home/kawai/ryu/ryu/tests/switch/tester.py", line 433, in _test_file_execute
    result = self._test_execute(test, desc)
  File "/home/kawai/ryu/ryu/tests/switch/tester.py", line 522, in _test_execute
    self._test(STATE_FLOW_UNMATCH_CHK, before_stats, pkt)
  File "/home/kawai/ryu/ryu/tests/switch/tester.py", line 598, in _test
    return test[state](*args)
  File "/home/kawai/ryu/ryu/tests/switch/tester.py", line 818, in _test_flow_unmatching_check
    before = before_stats[target_tbl_id]
KeyError: 1

--- Test terminated ---
